# Generated by Django 4.1.5 on 2023-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mybookings_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=200)),
                ('flight_date', models.DateField()),
                ('flight_time_depart', models.TimeField()),
                ('flight_time_arrival', models.TimeField()),
            ],
        ),
    ]
