# Generated by Django 4.1.5 on 2023-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_mybookings_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookings_data',
            name='flight_date',
            field=models.CharField(max_length=200),
        ),
    ]
